baseURL = "https://zengsansui.github.io/"
title = "Arielle"

# themes                     = "AllinOne"

builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 10


pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -140
    identifier             = "blog"
    url                    = "blog/"  
	
  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  


[params]
  # faviconfile              = "img/zheng.png"               # from static/
  # avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Arielle"
  description              = ["想了很久还是觉得，钱才是真正治愈心灵的良药鸭。"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 20                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = true                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "sansuizeng@foxmail.com"
  github                   = "https://github.com/zengsansui"
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon